"""

Primary:  Jamendo API — free, real MP3 direct links, works in India.
          Register free at https://devportal.jamendo.com → get client_id
          Add as JAMENDO_CLIENT_ID secret in GitHub.

Fallback: Free Music Archive CC0 direct MP3 links (no API needed).
Last:     Silent 30s audio generated by FFmpeg.
"""

import hashlib
import logging
import os
import subprocess
from pathlib import Path

import httpx

log = logging.getLogger("oracle.audio")

ASSETS_DIR = Path("assets/audio")
ASSETS_DIR.mkdir(parents=True, exist_ok=True)

JAMENDO_BASE      = "https://api.jamendo.com/v3.0"
JAMENDO_CLIENT_ID = os.environ.get("JAMENDO_CLIENT_ID", "")
VIDEO_DURATION    = 30

TOPIC_TAGS = {
    "stoicism":    ["meditation", "ambient", "calm"],
    "philosophy":  ["ambient", "atmospheric"],
    "motivation":  ["uplifting", "inspiring", "motivational"],
    "mindfulness": ["meditation", "zen", "peaceful"],
    "success":     ["uplifting", "positive"],
    "nature":      ["ambient", "nature", "peaceful"],
    "space":       ["atmospheric", "cinematic"],
    "technology":  ["electronic", "modern"],
    "fitness":     ["energetic", "workout"],
    "wisdom":      ["calm", "meditation"],
    "life":        ["ambient", "inspiring"],
    "love":        ["romantic", "calm"],
}

# CC0 verified direct MP3s — no API, no auth, no redirects
CC0_TRACKS = [
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Kai_Engel/Satin/Kai_Engel_-_01_-_Interplay.mp3",
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Kai_Engel/Sustains/Kai_Engel_-_08_-_Dream.mp3",
    "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Chad_Crouch/Arps_and_Runs/Chad_Crouch_-_Shipping_Lanes.mp3",
]


class AudioFetcher:
    def __init__(self):
        pass

    async def fetch(self, topic: str, post_type: str = "reel") -> Path:
        # 1. Try Jamendo API
        if JAMENDO_CLIENT_ID:
            for tag in self._get_tags(topic):
                try:
                    path = await self._jamendo_search(tag)
                    if path:
                        return path
                except Exception as e:
                    log.warning(f"Jamendo [{tag}] error: {e}")

        # 2. Try CC0 fallback tracks
        for url in CC0_TRACKS:
            try:
                path = await self._download(url)
                if path:
                    return path
            except Exception as e:
                log.warning(f"CC0 download error: {e}")

        # 3. Silent fallback
        log.info("All audio sources failed — silent fallback.")
        return self._make_silent()

    async def _jamendo_search(self, tag: str) -> Path | None:
        log.info(f"Jamendo search: tag={tag}")
        async with httpx.AsyncClient(timeout=30) as c:
            r = await c.get(
                f"{JAMENDO_BASE}/tracks/",
                params={
                    "client_id":   JAMENDO_CLIENT_ID,
                    "format":      "json",
                    "limit":       "5",
                    "tags":        tag,
                    "audioformat": "mp32",
                    "order":       "popularity_total",
                },
            )
        tracks = r.json().get("results", [])
        if not tracks:
            log.warning(f"Jamendo: no results for tag={tag}")
            return None

        for track in tracks:
            url = track.get("audio") or track.get("audiodownload")
            if url:
                log.info(f"Jamendo track: {track.get('name')} — {url[:70]}")
                return await self._download(url)
        return None

    async def _download(self, url: str) -> Path | None:
        cached = ASSETS_DIR / f"{hashlib.md5(url.encode()).hexdigest()[:10]}.mp3"
        if cached.exists():
            log.info(f"Audio cache: {cached}")
            return cached

        async with httpx.AsyncClient(timeout=60, follow_redirects=True) as c:
            r = await c.get(url)

        ct = r.headers.get("content-type", "")
        if r.status_code == 200 and "audio" in ct and len(r.content) > 10_000:
            cached.write_bytes(r.content)
            log.info(f"Audio saved: {cached} ({len(r.content)//1024} KB)")
            return cached

        log.warning(f"Download failed: HTTP {r.status_code} ct={ct} size={len(r.content)}")
        return None

    def _get_tags(self, topic: str) -> list[str]:
        t = topic.lower()
        for kw, tags in TOPIC_TAGS.items():
            if kw in t:
                return tags
        return ["ambient", "calm"]

    def _make_silent(self) -> Path:
        out = ASSETS_DIR / "silent_30s.mp3"
        if not out.exists():
            subprocess.run([
                "ffmpeg", "-y", "-f", "lavfi",
                "-i", "anullsrc=channel_layout=stereo:sample_rate=48000",
                "-t", str(VIDEO_DURATION),
                "-q:a", "9", "-acodec", "libmp3lame", str(out),
            ], capture_output=True)
        return out