"""
core/audio_fetcher.py
Fetches CC0-licensed background music using direct MP3 downloads.
No API key required. Uses curated list of freepd.com CC0 tracks.
Falls back to silent audio generated by FFmpeg.
"""

import asyncio
import hashlib
import logging
import os
import random
import subprocess
from pathlib import Path

import httpx

log = logging.getLogger("oracle.audio")

ASSETS_DIR = Path("assets/audio")
ASSETS_DIR.mkdir(parents=True, exist_ok=True)

# Duration for post types (seconds)
AUDIO_DURATION = {"reel": 30, "feed": 15}

# Curated CC0 tracks from freepd.com — direct MP3 URLs, no API needed
# All tracks are Public Domain / CC0 licensed
CC0_TRACKS = {
    "meditation": [
        "https://freepd.com/music/Meditation%20Impromptu%2001.mp3",
        "https://freepd.com/music/Dreamy%20Flashback.mp3",
        "https://freepd.com/music/Ascending%20the%20Vale.mp3",
    ],
    "ambient": [
        "https://freepd.com/music/Chill%20Day.mp3",
        "https://freepd.com/music/Dreamy%20Flashback.mp3",
        "https://freepd.com/music/White%20River.mp3",
    ],
    "uplifting": [
        "https://freepd.com/music/Wakka%20Wakka.mp3",
        "https://freepd.com/music/Funky%20Chunk.mp3",
        "https://freepd.com/music/Positive%20Motivation.mp3",
    ],
    "cinematic": [
        "https://freepd.com/music/Ascending%20the%20Vale.mp3",
        "https://freepd.com/music/Dreamy%20Flashback.mp3",
        "https://freepd.com/music/White%20River.mp3",
    ],
    "default": [
        "https://freepd.com/music/Meditation%20Impromptu%2001.mp3",
        "https://freepd.com/music/Chill%20Day.mp3",
        "https://freepd.com/music/Ascending%20the%20Vale.mp3",
        "https://freepd.com/music/Dreamy%20Flashback.mp3",
    ],
}

# Topic → mood mapping
TOPIC_MOOD_MAP = {
    "stoicism": "meditation",
    "philosophy": "ambient",
    "motivation": "uplifting",
    "mindfulness": "meditation",
    "success": "uplifting",
    "nature": "ambient",
    "space": "cinematic",
    "technology": "ambient",
    "fitness": "uplifting",
    "wisdom": "meditation",
    "life": "ambient",
}


class AudioFetcher:
    def __init__(self):
        pass  # No API key needed anymore

    async def fetch(self, topic: str, post_type: str = "reel") -> Path:
        """
        Download a CC0 background music track relevant to the topic.
        Returns path to downloaded .mp3 file.
        """
        mood = self._get_mood(topic)
        tracks = CC0_TRACKS.get(mood, CC0_TRACKS["default"])
        track_url = random.choice(tracks)

        # Cache by URL hash
        url_hash = hashlib.md5(track_url.encode()).hexdigest()[:8]
        output_path = ASSETS_DIR / f"{url_hash}.mp3"

        if output_path.exists():
            log.info(f"Audio cache hit: {output_path}")
            return output_path

        # Try downloading the track
        log.info(f"Downloading CC0 track [{mood}]: {track_url}")
        try:
            async with httpx.AsyncClient(
                timeout=60.0,
                follow_redirects=True
            ) as client:
                r = await client.get(track_url)
                if r.status_code == 200 and len(r.content) > 10000:
                    output_path.write_bytes(r.content)
                    log.info(f"Audio saved: {output_path} ({len(r.content)/1024:.0f} KB)")
                    return output_path
                else:
                    log.warning(f"Track download failed: HTTP {r.status_code} size={len(r.content)}")
        except Exception as e:
            log.warning(f"CC0 track download error: {e}")

        # Try other tracks in same mood
        for fallback_url in tracks:
            if fallback_url == track_url:
                continue
            try:
                fb_hash = hashlib.md5(fallback_url.encode()).hexdigest()[:8]
                fb_path = ASSETS_DIR / f"{fb_hash}.mp3"
                if fb_path.exists():
                    return fb_path
                async with httpx.AsyncClient(
                    timeout=60.0,
                    follow_redirects=True
                ) as client:
                    r = await client.get(fallback_url)
                    if r.status_code == 200 and len(r.content) > 10000:
                        fb_path.write_bytes(r.content)
                        log.info(f"Fallback audio saved: {fb_path}")
                        return fb_path
            except Exception as e:
                log.warning(f"Fallback track failed: {e}")
                continue

        # Last resort: silent audio via FFmpeg
        log.info("All audio downloads failed. Generating silent fallback.")
        return self._generate_silent(post_type, url_hash)

    def _get_mood(self, topic: str) -> str:
        """Map topic to music mood."""
        topic_lower = topic.lower()
        for keyword, mood in TOPIC_MOOD_MAP.items():
            if keyword in topic_lower:
                return mood
        return "default"

    def _generate_silent(self, post_type: str, cache_key: str) -> Path:
        """Generate a silent MP3 track as absolute last-resort fallback."""
        duration = AUDIO_DURATION.get(post_type, 30)
        output_path = ASSETS_DIR / f"{cache_key}_silent.mp3"

        cmd = [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", "anullsrc=channel_layout=stereo:sample_rate=44100",
            "-t", str(duration),
            "-q:a", "9",
            "-acodec", "libmp3lame",
            str(output_path),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(f"FFmpeg silent audio failed: {result.stderr}")
        return output_path