"""
core/audio_fetcher.py
Fetches CC0-licensed background music from Internet Archive (FreePD collection).
FreePD.com shut down — all tracks are preserved at archive.org/details/freepd
All tracks are Public Domain / CC0. No API key needed.
Falls back to silent audio generated by FFmpeg.
"""

import asyncio
import hashlib
import logging
import random
import subprocess
from pathlib import Path

import httpx

log = logging.getLogger("oracle.audio")

ASSETS_DIR = Path("assets/audio")
ASSETS_DIR.mkdir(parents=True, exist_ok=True)

AUDIO_DURATION = {"reel": 30, "feed": 15}

# Direct MP3 URLs from Internet Archive FreePD collection
# archive.org/details/freepd — all Public Domain / CC0
CC0_TRACKS = {
    "meditation": [
        "https://archive.org/download/freepd/Meditation%20Impromptu%2001.mp3",
        "https://archive.org/download/freepd/Dreamy%20Flashback.mp3",
        "https://archive.org/download/freepd/Chill%20Day.mp3",
    ],
    "ambient": [
        "https://archive.org/download/freepd/Chill%20Day.mp3",
        "https://archive.org/download/freepd/White%20River.mp3",
        "https://archive.org/download/freepd/Dreamy%20Flashback.mp3",
    ],
    "uplifting": [
        "https://archive.org/download/freepd/Funky%20Chunk.mp3",
        "https://archive.org/download/freepd/Wakka%20Wakka.mp3",
        "https://archive.org/download/freepd/Positive%20Motivation.mp3",
    ],
    "cinematic": [
        "https://archive.org/download/freepd/Ascending%20the%20Vale.mp3",
        "https://archive.org/download/freepd/Dreamy%20Flashback.mp3",
        "https://archive.org/download/freepd/White%20River.mp3",
    ],
}

TOPIC_MOOD_MAP = {
    "stoicism": "meditation",
    "philosophy": "ambient",
    "motivation": "uplifting",
    "mindfulness": "meditation",
    "success": "uplifting",
    "nature": "ambient",
    "space": "cinematic",
    "technology": "ambient",
    "fitness": "uplifting",
    "wisdom": "meditation",
    "life": "ambient",
}


class AudioFetcher:
    def __init__(self):
        pass

    async def fetch(self, topic: str, post_type: str = "reel") -> Path:
        mood = self._get_mood(topic)
        tracks = CC0_TRACKS.get(mood, CC0_TRACKS["meditation"])

        # Try each track in shuffled order
        shuffled = random.sample(tracks, len(tracks))
        for url in shuffled:
            url_hash = hashlib.md5(url.encode()).hexdigest()[:8]
            cached = ASSETS_DIR / f"{url_hash}.mp3"
            if cached.exists():
                log.info(f"Audio cache hit: {cached}")
                return cached
            try:
                log.info(f"Downloading CC0 [{mood}]: {url.split('/')[-1]}")
                async with httpx.AsyncClient(timeout=60.0, follow_redirects=True) as client:
                    r = await client.get(url)
                    if r.status_code == 200 and len(r.content) > 10_000:
                        cached.write_bytes(r.content)
                        log.info(f"Audio saved: {cached} ({len(r.content)//1024}KB)")
                        return cached
                    log.warning(f"Bad response: HTTP {r.status_code} size={len(r.content)}")
            except Exception as e:
                log.warning(f"Download failed: {e}")

        log.info("All audio downloads failed. Generating silent fallback.")
        return self._generate_silent(post_type)

    def _get_mood(self, topic: str) -> str:
        topic_lower = topic.lower()
        for keyword, mood in TOPIC_MOOD_MAP.items():
            if keyword in topic_lower:
                return mood
        return "meditation"

    def _generate_silent(self, post_type: str) -> Path:
        duration = AUDIO_DURATION.get(post_type, 30)
        output_path = ASSETS_DIR / f"silent_{duration}s.mp3"
        if output_path.exists():
            return output_path
        cmd = [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", "anullsrc=channel_layout=stereo:sample_rate=44100",
            "-t", str(duration),
            "-q:a", "9",
            "-acodec", "libmp3lame",
            str(output_path),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(f"FFmpeg silent audio failed: {result.stderr}")
        return output_path